### ISSUE TITLE
Prometheus as db for port_state watcher throws NoneType error

### ISSUE THREAD

**Issue by shivarammysore** [faucetsdn/faucet#1138]
In gauge.yaml, I have watcher configured as:

  ```
 port_status_poller:
       type: 'port_state'
       dps: ['ovs-qotom-allbirds-1']
       db: 'prometheus'
```
Per my understanding, ```port_state``` is a valid supported type for prometheus.  But, I get the below error in log files.  BTW, changing db to Influx makes the error go away.

 ```
 File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/gauge.py", line 106, in _load_config
    watcher = watcher_factory(conf)(conf, self.logname, self.prom_client)
TypeError: 'NoneType' object is not callable
```

**Comment by gizmoguy** [comment]
In prometheus the data model is a bit different, prometheus polls us for data rather than us pushing so we can be a bit more dumb in how we handle things like port_state.

How we've implemented this currently is that faucet provides a "port_status" metric that prometheus scrapes rather than using gauge to constantly watch for port events. If you simply setup your prometheus to scrape your faucet controller then this new metric should just show up with no further configuration.

**Comment by shivarammysore** [comment]
Thanks Brad for the clarification.

In summary, what you are stating is that Gauge's port_state watcher is
similar to what we get via Faucet being polled by Prometheus.

**Comment by gizmoguy** [comment]
So yeah, the end result is the same you get the current (and a timeseries of) the port states on your DPs.

The implementation is quite different, pull vs push.

**Comment by shivarammysore** [comment]
Thanks very much for the clarification
