### ISSUE TITLE
stacked configuration does not fully learn broadcast flows

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/faucet#1569]
A stacked configuration does not properly learn all broadcast flows, and so continually generates packet-in messages on each broadcast. This would be a problem in a system with extensive use of broadcast, since it would swap the controller.

The problem seems to be that a non-root switch (secondary?) doesn't learn the eth_src properly. The controller spits out a message that the switch learns the L2 address, but table 3 doesn't update to reflect the change. Because of the way stacking/broadcast works, I think the rules get confused because the src address enters on both the "downstream" port, but then also again from the "upstream" port as it's reflected back by the stack root.

The same general configuration works fine when stacking is not enabled.

**Comment by trungdtbk** [comment]
Can you share your config?

**Comment by grafnu** [comment]
Here's [faucet-stacked.yaml.txt](https://github.com/faucetsdn/faucet/files/1669642/faucet-stacked.yaml.txt) -- it's pretty much the simplest config you can imagine for this.

**Comment by anarkiwi** [comment]
Thanks for reporting this. 

The bug was that when we receive the return flooded packet from the stack port, we tried to learn it again. We can filter that out, for stack ports specifically, by not learning broadcast destinations (they're just handed off to the flood table straight away).

As an additional benefit, this means that if an edge switch gets broadcasts from other switches, it won't bother learning the remote host unless the remote host unicasts to one of the connected hosts. This is a nice scaling property - edge switches will only learn hosts that talk to local ones.

https://github.com/faucetsdn/faucet/commit/383dc2269c891da8b600d7077024bedadf91dc28



**cookie=0x5adc15c0, duration=18.964s, table=3, n_packets=34, n_bytes=1564, priority=9099,in_port=5,dl_vlan=100,dl_dst=ff:ff:ff:ff:ff:ff actions=goto_table:8
 cookie=0x5adc15c0, duration=19.023s, table=3, n_packets=24, n_bytes=1776, priority=9099,in_port=5,dl_vlan=100,dl_dst=33:33:00:00:00:00/ff:ff:00:00:00:00 actions=goto_table:8
 cookie=0x5adc15c0, duration=19.022s, table=3, n_packets=0, n_bytes=0, priority=9099,in_port=5,dl_vlan=100,dl_dst=01:80:c2:00:00:00/ff:ff:ff:00:00:00 actions=goto_table:8
 cookie=0x5adc15c0, duration=19.021s, table=3, n_packets=0, n_bytes=0, priority=9099,in_port=5,dl_vlan=100,dl_dst=01:00:5e:00:00:00/ff:ff:ff:00:00:00 actions=goto_table:8
 cookie=0x5adc15c0, duration=19.021s, table=3, n_packets=0, n_bytes=0,** priority=9099,dl_src=ff:ff:ff:ff:ff:ff actions=drop
 cookie=0x5adc15c0, duration=19.021s, table=3, n_packets=0, n_bytes=0, priority=9001,dl_src=0e:00:00:00:00:01 actions=drop
 cookie=0x5adc15c0, duration=16.720s, table=3, n_packets=70, n_bytes=5880, hard_timeout=297, priority=9098,in_port=1,dl_vlan=100,dl_src=22:9c:62:c1:40:8d actions=goto_table:7
 cookie=0x5adc15c0, duration=16.204s, table=3, n_packets=67, n_bytes=5574, hard_timeout=298, priority=9098,in_port=3,dl_vlan=100,dl_src=36:90:cb:73:48:64 actions=goto_table:7
 cookie=0x5adc15c0, duration=16.204s, table=3, n_packets=67, n_bytes=5574, hard_timeout=299, priority=9098,in_port=4,dl_vlan=100,dl_src=2a:fc:5a:6e:7c:3e actions=goto_table:7
 cookie=0x5adc15c0, duration=15.695s, table=3, n_packets=67, n_bytes=5574, hard_timeout=305, priority=9098,in_port=2,dl_vlan=100,dl_src=aa:7d:d2:2c:e6:8c actions=goto_table:7
 cookie=0x5adc15c0, duration=14.656s, table=3, n_packets=25, n_bytes=1990, hard_timeout=300, priority=9098,in_port=5,dl_vlan=100,dl_src=f2:ee:fd:21:b5:d1 actions=goto_table:7
 cookie=0x5adc15c0, duration=14.648s, table=3, n_packets=25, n_bytes=1990, hard_timeout=298, priority=9098,in_port=5,dl_vlan=100,dl_src=ea:07:6d:11:11:16 actions=goto_table:7
 cookie=0x5adc15c0, duration=14.642s, table=3, n_packets=27, n_bytes=2194, hard_timeout=299, priority=9098,in_port=5,dl_vlan=100,dl_src=36:57:86:7c:12:85 actions=goto_table:7
 cookie=0x5adc15c0, duration=14.632s, table=3, n_packets=27, n_bytes=2194, hard_timeout=295, priority=9098,in_port=5,dl_vlan=100,dl_src=d6:ff:4b:0c:ef:28 actions=goto_table:7
 cookie=0x5adc15c0, duration=14.598s, table=3, n_packets=46, n_bytes=3124, hard_timeout=305, priority=9098,in_port=5,dl_vlan=100,dl_src=de:ad:9d:ab:ea:de actions=goto_table:7
 cookie=0x5adc15c0, duration=14.576s, table=3, n_packets=34, n_bytes=2404, hard_timeout=300, priority=9098,in_port=5,dl_vlan=100,dl_src=ee:62:b8:6c:36:ca actions=goto_table:7
 cookie=0x5adc15c0, duration=14.571s, table=3, n_packets=31, n_bytes=2266, hard_timeout=302, priority=9098,in_port=5,dl_vlan=100,dl_src=92:5c:eb:4e:9f:55 actions=goto_table:7
 cookie=0x5adc15c0, duration=14.376s, table=3, n_packets=26, n_bytes=1980, hard_timeout=301, priority=9098,in_port=5,dl_vlan=100,dl_src=f6:ab:f5:e6:e4:69 actions=goto_table:7
