### ISSUE TITLE
Interface mirroring doesn't mirror broadcast packets in stacked configuration

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/faucet#1623]
Interface mirroring doesn't mirror output broadcast packets in a stacked configuration. I think this is because in a stacked configuration, a broadcast packet ends up coming from the upstream stacked port rather than a normal source port. Not sure why, but I think that trips up the logic.

**Comment by anarkiwi** [comment]
Thanks for reporting this - fixed in https://github.com/faucetsdn/faucet/commit/d57c08d166891e415922e00ed62d506a9e1653a6.

We had a long standing bug that affected non-stacking as well - broadcasts destined to a mirrored port were not mirrored, and we made an extra copy of broadcasts from a mirrored port.
