### ISSUE TITLE
need separate packet-in rate limits for host learning and CP-specifics

### ISSUE THREAD

**Issue by trungdtbk** [faucetsdn/faucet#1834]
A same rate-limit is used for all types of packet-ins, while their importance is different.
During heavy load periods, CP-specific packet-ins like arp requests and lldp are silently ignored.

**Comment by anarkiwi** [comment]
The priority order is not well characterized. ARP, LLDP etc are all retried. Learning is retried too (if load is too high, dataplane flooding occurs so that packets are still forwarded until the controller can recover). If there is a particular case where high load is not handled well today, or in a way where some priority ordering would improve that, please reopen the issue with details.
