### ISSUE TITLE
Refactor faucet test suite

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#2118]
This ticket will cover the first round of refactoring the test suite.

The goal at the end of this ticket is to have:

  1. Different tests (clib, unit tests, integration tests) groups together in a nice directory structure
  2. File names make it obvious what the file does and how to kick off each test

**Comment by lantz** [comment]
I will await clarification on this. ;-)

**Comment by gizmoguy** [comment]
Hi @lantz, sorry for going silent for a bit there, had a power outage at one of my work facilities followed by a long lunch meeting. I am here for the next 4 hours to help.

I came up with some ideas here, ultimately it looks like you've had some good ideas so I suspect we will mash my ideas with yours to come up with a final product.

So I came up with creating ``tests/unit`` and ``tests/integration`` (though I like your ``tests/codecheck`` as well or maybe ``tests/lint``?). I think for now we will have to keep clib where it is, we have subprojects which depend on this namespace (``faucet.clib``) so we'd need to communicate with the project leads at these other projects and get them to change to the new directory location which I don't want you to have to waste your time on.

My proposed file names and file moves looked like this:

| File/Directory | Change |
| --- | --- |
| tests/config/ | Delete (unused) |
| tests/test_*.py | Move to tests/unit/ |
| tests/fakeoftable.py | Move to tests/unit/ |
| tests/faucet_mininet_test.py | Move to tests/mininet_main.py |
| tests/faucet_mininet_test_unit.py | Move to tests/integration/mininet_tests.py |
| tests/test_coverage.sh | Rename to tests/run_unit_tests.sh |
| tests/all_tests.sh | Rename to tests/run_integration_tests.sh |
| tests/all_zodiac_tests.sh | Rename to tests/run_zodiac_integration_tests.sh |
| tests/test_min_pylint.sh | Rename to tests/pylint.sh |
| tests/test_pytype.sh | Rename to tests/pytype.sh |

Please let me know what you think of these.

**Comment by lantz** [comment]
Looks reasonable to me. My additional thoughts are:

- Would it make sense to have a `lint` directory (not sure if that's the best name but I am OK with it to start with) for the (two) static code checks, or should they stay at the top level?

- Would it make sense for `mininet_test_main.py` to go in `integration` rather than at the top level?

**Comment by gizmoguy** [comment]
Upon further reflection, let's go with your original ``codecheck/`` instead of ``lint/`` and yes let's move pylint.sh and pytype.sh there.

Okay let's also move ``mininet_main.py`` to ``integration/``and ``fakeoftable.py`` to ``unit/``

I can confirm that ``config/`` is part of an older system that we no longer use so it can be removed.

**Comment by lantz** [comment]
Works for me.

**Comment by lantz** [comment]
Created pull request #2135 

It differs slightly from the above:

- Instead of `integration/mininet_main.py` I thought that sticking with `faucet_mininet_test.py` would match `clib_mininet_test.py`

- `clib/mininet_test.py` has been renamed `clib/mininet_test_main.py` as this seemed to reflect what it was; the comment is still wrong and implies that it can be run directly.

- unfortunately renaming files in `clib/` changes the API and may break clients that use the modules that have been renamed
