### ISSUE TITLE
802.1x reauth interval

### ISSUE THREAD

**Issue by anarkiwi** [faucetsdn/faucet#2831]
We would like to be able to re-auth a port periodically, even if the port doesn't change op status.

**Comment by Bairdo** [comment]
Is this going to be initiated from the faucet side (not the supplicant)?
And before the supplicant session expires?

Is this different from the session timeout mechanism where after X seconds the supplicant becomes deauthenticated. (Is it an extension so that at X sec faucet/chewie starts a reauth? In which case https://github.com/faucetsdn/chewie/issues/46 (essentially allowing Chewie to start authentication via sending the Identity Request without a EAPOL-Start from the supplicant) would likely achieve this).

**Comment by Bairdo** [comment]
How long a interval?

Should it be directed at the authenticated supplicants MAC address, or everyone on the port?
