### ISSUE TITLE
Providing options to runtests.sh

### ISSUE THREAD

**Issue by MichaelWasher** [faucetsdn/faucet#3364]
Runtests.sh receives it's options for which tests to run through the FAUCET_TESTS environment variable.

This variable is then passed to the 'mininet_main.py' application which will receive and understand a subset of the options however no options are removed from $FAUCET_TESTS before it's piped as options for mininet_main.

This means that '-z -i' can't be used together, and '-u' or '-nu' doesn't work according to the documentation as integration tests don't spin up automatically.

An example fix for this is here (NOTE: this is not a real solution as it will kill all lowercase 'uzn' characters):
https://github.com/MichaelWasher/faucet/tree/fix_fast_integration_tests

I don't like the idea of the fix; better solution would be to use something similar to `shift`, `OPTIND` or adding passthrough options to a separate variable for consumption by mininet_tests. 

I'm not big on bash so just ideas.

**Comment by gizmoguy** [comment]
Okay yeah, I had been having a think about how to do this better a couple weeks back and I never got anywhere with it, mostly due to me refusing to read the getopt man page and remember how it works.

This bug also prevents the long version of the arguments from being parsed correctly as well (e.g `--clean` and `--nocheck`).

I have accepted this ticket now and will look at getting a fix in as quick as I can.

**Comment by gizmoguy** [comment]
Okay, give that PR a go and see if it fixes the issue for you.
